### ISSUE TITLE
docker exec -it 9a5c836d34f0 -c 'osm2pgrouting -f FORTALEZA.osm -h 172.19.0.3 -p 5432 -d routing'           OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"-c\": executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by stings8** [Starefossen/docker-pgrouting#25]
how do i run a command to import data with osm2pgrouting?
I use this command:
docker exec -it 9a5c836d34f0 -c 'osm2pgrouting -f FORTALEZA.osm -h 172.19.0.3 -p 5432 -d routing' bash

and I get this error:
docker exec -it 9a5c836d34f0 -c 'osm2pgrouting -f FORTALEZA.osm -h 172.19.0.3 -p 5432 -d routing'           OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"-c\": executable file not found in $PATH": unknown

**Comment by michaelb87** [comment]
not sure what "docker exec -c" would do.
Here are the official docs https://docs.docker.com/engine/reference/commandline/exec/

(hint try to add "bash " before -c or just get a shell in your docker container and go from there.
