### ISSUE TITLE
PGRouting 2.1.0

### ISSUE THREAD

**Issue by bteres** [Starefossen/docker-pgrouting#3]
It seems that there is no docker file for pgrouting 2.1.0. Is there an easy way to get pgrouting 2.1.0 in this container?

**Comment by Starefossen** [comment]
Good observation @bteres 👍🏼 I'll push out a new version tonight

**Comment by bteres** [comment]
## Awesome. Looking forward to it. I need some functions from 2.1 and couldn't get my own modification working. 

Sent from myMail app for Android Tuesday, 12 January 2016, 06:22PM +02:00 from Hans Kristian Flaatten < notifications@github.com> :

**Comment by bteres** [comment]
Any update on this @Starefossen?

**Comment by Starefossen** [comment]
Yeah, sorry about the wait. Looks like I need to compile this from source or find some maintainer that can put it into the Debian package registry :confused:

**Comment by bteres** [comment]
That's what I thought. Let me know if you have any luck with this. I'll also try have a look today and will submit a pull request if I get it right.

**Comment by Starefossen** [comment]
There is the chat log from my conversation with one of the pgRouting developers yesterday:

> Starefossen 09:58
> Can I install pgRouting form https://launchpad.net/~georepublic/+archive/ubuntu/pgrouting on Debian Jessie?
> 
> cvvergara 14:59
> Never tried, we don't know...
> why dont you give it a try and let us know.
> Otherwise you would need to download it from github.
> 
> Starefossen 15:05
> Thank you. Will report back with my results. No other Debian repo with pgRouring v2.1 as you know of?
> 
> cvvergara 15:08
> As far as my memory goes its the only repository for debian.
> There are builds for Centos and windows

**Comment by bteres** [comment]
It is in the unstable repository. I have it working and am submitting a pull request now.
