### ISSUE TITLE
Add osm2pgrouting to the installation

### ISSUE THREAD

**Issue by milovanderlinden** [Starefossen/docker-pgrouting#8]
Can simply be installed by adding it to the apt-get install section. This way a great tool would be available within the image to import osm files. I suggest also adding wget so downloading osm files and importing them into the database can be done from within the image.

**Comment by milovanderlinden** [comment]
Thanks for that!

**Comment by ghost** [comment]
What package repository would this be in?

I've added the apt.postgresql.org repo, but docker complains that it can't find the package osm2pgrouting.

**Comment by Starefossen** [comment]
@hpfast looks like upstream (Postgres) moved to debian:jessie as their base image which does not have a package for `osm2pgrouting`. Will remove the package to get Docker Hub builds working again.

**Comment by ghost** [comment]
Ok, that explains it, thanks. Hadn't thought to look in debian's repos.
Managing to build from source.
